# Pipeline for the IMS project used for testing continuesly testing

name: Testing IMS

on:
  push:
    branches: [ "main", "pipeTest" ]
  pull_request:
    branches: [ "main", "pipeTest" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
    - name: Setup of nodejs miljø ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./ims/package-lock.json

    - name: Install required dependencies
      run: npm ci
      working-directory: ims

    - name: Build angular project
      run: npm run build
      working-directory: ims
      
    - name: Run tests
      run: npm run test
      working-directory: ims
