# Pipeline for the IMS project used for testing continuesly testing

name: Node.js CI

on:
  push:
    branches: [ "main", "pipeTest" ]
  pull_request:
    branches: [ "main", "pipeTest" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
    - name: Setup of nodejs miljø ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: locate the project
      run: cd ims

    - name: Install required dependecies
      run: npm ci 
      
    - name: Build angular project
      run: npm run build
      
    - name: Run tests
      run: npm run test
